### PR TITLE
Cleanup multus conf on exit

### PR DESCRIPTION
**Pull request by adrianchiris**
- if cleanup-config-on-exit is set delete generated multus
  config file on exit.

- add an option to skip watch for master cni config and kubeconfig
  as cleanup-config-on-exit with multus-conf-file=auto also triggered
  the watch for cases when deletion of multus config is desired but watch isnt

- setup signal handling to allow config file cleanup on exit

### CODE REVIEW

**Comment by adrianchiris** [comment]
This is a proposed alternative to : #1298

as we used to clean up multus conf file in preStop hook, however since the container no longer has shell we cannot run simple sh commands for cleanup.

**Comment by dougbtv** [comment]
Let's add some notes about the flags @ https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#entrypoint-script-parameters

**Comment by adrianchiris** [comment]
@dougbtv docs update. 

additional feedback/review appreciated :)

**Comment by seastco** [comment]
@dougbtv @adrianchiris ty for landing this.

I take it disabling the watch functionality is necessary if CleanupConfigOnExit=true and MultusConfFile=auto because the file may be recreated before we're able to completely exit? this seems like CleanupConfigOnExit and watch are incompatible, which is unfortunate because I need both.

could we instead send a signal to the watch loop to stop before CleanupConfigOnExit is called? I'm thinking something like 
```
stopWatchChan := make(chan bool)

if opt.CleanupConfigOnExit {
        defer func() {
            stopWatchChan <- true // Send a stop signal to the watch loop
            cleanupMultusConf(&opt)
        }()
}
```

**Comment by adrianchiris** [comment]
@seastco there is a select statement on signal handler context.  cleanup config on exit should work both if watching or not.

the "skip-config-watch" flag was added to preserve backward compatibility since cleanup config on exit originally triggered the watch for some reason (imo it shouldnt and is counter intuitive), but it is what it is.

**Pull request merged**
