### PR TITLE
Bump ginkgo to v2

### PR DESCRIPTION
**Pull request by liornoy**
This PR updates the Ginkgo lib to version 2.5.1.

### CODE REVIEW

**Comment by liornoy** [comment]
@dougbtv Can you please review this PR?
This is part of an effort to bump all of the CNF projects to ginkgo v2, which was released a long time ago.

**Comment by liornoy** [comment]
fixed the modules.txt (go mod vendor).

**Comment by s1061123** [comment]
@liornoy could you please rebase to the latest master, to fix the failed CI build?

**Comment by liornoy** [comment]
> @liornoy could you please rebase to the latest master, to fix the failed CI build?

sure, done.

**Comment by s1061123** [comment]
hmm... this change updates 'golang.org/x/sys/unix' and this update makes build failed in golang1.16, which is done in origin.

@dougbtv Do you have any idea for that?

**Comment by s1061123** [comment]
Talked offline with @dougbtv and we conclude that we remove origin build from github action. Wait for a while to finish it.

**Comment by dougbtv** [comment]
I'm OK merging without the origin build succeeding, it appears to be a different issue regarding the out-of-date image. We'll address that separately as Tomo mentioned. Thanks!

**Review by dougbtv — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
