### PR TITLE
Modify the judgment of test results

### PR DESCRIPTION
**Pull request by yulng**
modify test-simple-macvlan1.sh

### CODE REVIEW

**Comment by s1061123** [comment]
Hi @yulng , thank you for your PR, again! Could you please explain why you need the changes? I understand what the code does, but I'd like to know why you need to add it.

**Comment by yulng** [comment]
> Hi @yulng , thank you for your PR, again! Could you please explain why you need the changes? I understand what the code does, but I'd like to know why you need to add it.

Confirm whether the network card name of the pod is net1, and return the result through "echo"

**Comment by yulng** [comment]
> > Hi @yulng , thank you for your PR, again! Could you please explain why you need the changes? I understand what the code does, but I'd like to know why you need to add it.
> 
> Confirm whether the network card name of the pod is net1, and return the result through "echo"

@s1061123

**Review by s1061123 — COMMENTED** [review]
I got it. If you don't mind it, please add 'exit 1' in case of 'no net1' interface, because 'no net1 interface' case, we just send error.

**Comment by yulng** [comment]
> I got it. If you don't mind it, please add 'exit 1' in case of 'no net1' interface, because 'no net1 interface' case, we just send error.

ok,if no net1, return the execution result of the command
modified

**Comment by yulng** [comment]
> > I got it. If you don't mind it, please add 'exit 1' in case of 'no net1' interface, because 'no net1 interface' case, we just send error.
> 
> ok,if no net1, return the execution result of the command modified

@s1061123

**Comment by s1061123** [comment]
@yulng sorry, but I mean that 'if no net1 case, just `exit 1`'. Because if there is no net1, then it must be error hence CI should be stopped with 'explicitly error'. In github action, non 'exit 0' cases are recognized as error.

So please add `exit 1` in case of 'no net1' case, for two places.

**Comment by yulng** [comment]
> @yulng sorry, but I mean that 'if no net1 case, just `exit 1`'. Because if there is no net1, then it must be error hence CI should be stopped with 'explicitly error'. In github action, non 'exit 0' cases are recognized as error.
> 
> So please add `exit 1` in case of 'no net1' case, for two places.

Okay, it's added











































































ok, added

**Pull request merged**
