### PR TITLE
Limit HTTP server's concurrency using semaphore.

### PR DESCRIPTION
**Pull request by juliusmh**
Signed-off-by: Julius Hinze <juliusmh@proton.me>

Closes: https://github.com/k8snetworkplumbingwg/multus-cni/issues/1346

### CODE REVIEW

**Comment by dougbtv** [comment]
Overall, I'm in favor of it, and I like that it's parameterized, but I'd like to see that pods do eventually come up in a situation where there's more than the concurrency limit, I believe those pods would crash loop?

I think maybe we should have some testing for it, best case scenario: e2e tests that both capture the error and the success.

**Comment by dougbtv** [comment]
Tomo also suggested taking a look at the limiters on https://pkg.go.dev/golang.org/x/net/netutil

**Comment by juliusmh** [comment]
> Overall, I'm in favor of it, and I like that it's parameterized, but I'd like to see that pods do eventually come up in a situation where there's more than the concurrency limit, I believe those pods would crash loop?
> 
> I think maybe we should have some testing for it, best case scenario: e2e tests that both capture the error and the success.

These pods would wait as the semaphore blocks, until the shim timeouts the requests. In this case the pod will fail and kubelet try again in the future. 

We should decide if we want to
- fail the HTTP request if concurrency is too high, retry from shim
- semaphore on listener level (`LimitListener`) or inside the handler (this PR)

**Comment by juliusmh** [comment]
@dougbtv fixed unit test & rebased

**Comment by s1061123** [comment]
I suppose using `LimitListener`, we don't need to introduce semaphore because `LimitListener` does the same things. Can we close it and proceed #1356?

**Comment by juliusmh** [comment]
Closing in favor of https://github.com/k8snetworkplumbingwg/multus-cni/pull/1356

**Pull request closed without merging**
