### PR TITLE
Fix for CRIO Thin Client Installations

### PR DESCRIPTION
**Pull request by rwlove**
1. Use the correct entrypoint

2. Use /opt/cni/bin for CNI bin dir

### CODE REVIEW

**Comment by maiqueb** [comment]
@s1061123 does this separate crio daemonset spec even makes sense these days ?

**Review by s1061123 — COMMENTED** [review]
Thank you for the PR, @rwlove !

I make sense the entrypoint fix, however,  I'd like to keep '/usr/libexec/cni' for CNI path. There are two reason:

- '/usr/libexec/cni' is the default path of Fedora's CNI plugin path. In Fedora38, for example, `dnf install  containernetworking-plugins` installs CNI plugins into '/usr/libexec/cni'.
- If user uses '/opt/cni/bin' for CNI plugin path, user can use `multus-daemonset.yml` instead of `multus-daemonset-crio.yml` because now the difference between '....yml' and '...-crio.yml' (previously we have more difference but now only the CNI path).

So could you please revert the change of CNI path? Thank you again and in advance.

**Comment by rwlove** [comment]
I understand your feedback and I'll happily update the patch and send a new PR.

**Comment by rwlove** [comment]
did I update this correctly?

**Pull request closed without merging**
