### PR TITLE
Add support for CNI config version 1.0.0

### PR DESCRIPTION
**Pull request by brandond**
Bumps github.com/containernetworking/cni, github.com/containernetworking/plugins, and github.com/k8snetworkplumbingwg/network-attachment-definition-client

As part of recent updates to the k3s packaged version of Flannel we recently bumped the cniVersion in our configuration file to `1.0.0`, but it appears that multus does not support this version yet as it's still on `github.com/containernetworking/cni  v0.8.1` which only supports up to `v0.4.0`.

### CODE REVIEW

**Comment by brandond** [comment]
I'm not sure what the deal is with the JavaScript analysis? If someone could approve the rest of the workflows to run that'd be great.

**Comment by s1061123** [comment]
Thank you for the PR @brandond 

We are going to support CNI 1.0 at multus 4.0 release. Currently the release is pretty near from now.
Please wait for a while until multus release 4.0.

Development branch is in here and it contains CNI 1.0 support code, so you can test it.
https://github.com/k8snetworkplumbingwg/multus-cni/tree/feature/multus-4.0

Thank you again to submit the PR!

**Comment by liyimeng** [comment]
@s1061123 what is the date? being a cni project but support pretty old cni version. it is a shame :(

**Comment by s1061123** [comment]
@liyimeng we're likely to release 4.0 soon. But you can already use these code as above url, multus-cni which supports CNIVersion 1.0.0. We're ready but need a time a bit.

BTW, from functionality point of view, CNI version 0.4.0 and 1.0.0 is pretty similar. So I'd like to know why you want to use '1.0.0'. 
If you really want to use it with specific reason, I strongly recommend to use following branch to try multus 4.0 to test CNI version 1.0.0  because you could give a really good and 'real' feedback to us!

https://github.com/k8snetworkplumbingwg/multus-cni/tree/feature/multus-4.0

Appreciate the help and really looking forward to see your feedback, in advance!

**Comment by ivan4th** [comment]
k3s setup needs extra hacks b/c support for CNI 1.0.0 is missing:
https://www.reddit.com/r/kubernetes/comments/10isjfd/k3s_v124/

**Comment by fancycode** [comment]
From what I can see in the commit history, https://github.com/k8snetworkplumbingwg/multus-cni/pull/893/commits/93ec0c121e8d53cb1b7c2fe33fa0158c388133f6 introduced support for CNI 1.0.0 (#893) and is part of the 4.0.x releases (https://github.com/k8snetworkplumbingwg/multus-cni/releases).

**Pull request closed without merging**
