### PR TITLE
branch master was renamed to main

### PR DESCRIPTION
**Pull request by panguicai008**

### CODE REVIEW

**Comment by s1061123** [comment]
As far as I looked branch pages in multus, `master` branch is default and there is no `main` branch. So your change is invalid, hence I close the PR. Thanks.

https://github.com/k8snetworkplumbingwg/multus-cni/branches

**Comment by panguicai008** [comment]
> multus

I modified branches of the following two projects，not multus-cni 
https://github.com/containernetworking/plugins
https://github.com/containernetworking/cni

**Comment by s1061123** [comment]
@panguicai008 thank you for the clarification. In such case, you need to refine commit message for that.

Your PR title and commit message are "branch master was renamed to main". This repository is about multus-cni, so if someone tell 'branch', then easily imagine 'multus repo branch'. Especially commit message shows 'what you did in the code', so your commit message should be aligned with actual change.

It is hard to write good commit message but it is important and of course it is required. So you can find several articles, how to write good commit message. Please read that and try to file another one, with good commit message.
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Comment by panguicai008** [comment]
> @panguicai008 thank you for the clarification. In such case, you need to refine commit message for that.
> 
> Your PR title and commit message are "branch master was renamed to main". This repository is about multus-cni, so if someone tell 'branch', then easily imagine 'multus repo branch'. Especially commit message shows 'what you did in the code', so your commit message should be aligned with actual change.
> 
> It is hard to write good commit message but it is important and of course it is required. So you can find several articles, how to write good commit message. Please read that and try to file another one, with good commit message. https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

thanks. i should write a good commit message

**Pull request closed without merging**
