### PR TITLE
add cniConf as multus entrypoint's parameter

### PR DESCRIPTION
**Pull request by cyclinder**
https://github.com/k8snetworkplumbingwg/multus-cni/issues/1118

### CODE REVIEW

**Comment by s1061123** [comment]
Could you please add same functionality into `image/enetrypoint.sh` to make consistency?

**Comment by cyclinder** [comment]
Yes, I'm working on this.

**Comment by cyclinder** [comment]
Hi @s1061123 Could you please take a look? I think the PR is ready.

**Comment by cyclinder** [comment]
Hi @s1061123 Could you please take a look?

**Comment by cyclinder** [comment]
Hi @s1061123 , This PR is ready for merge, Could you take a look? thanks.

**Comment by cyclinder** [comment]
Hi @s1061123, Could you take a look? thanks

**Pull request closed without merging**
