### PR TITLE
add unit test for exec_chroot_test

### PR DESCRIPTION
**Pull request by yulng**
add unit test for exec_chroot_test

### CODE REVIEW

**Comment by s1061123** [comment]
Will take a look into it next week.

**Comment by yulng** [comment]
> Will take a look into it next week.

@s1061123

**Comment by s1061123** [comment]
Thank you for the PR, @yulng . Looking coveralls, https://github.com/k8snetworkplumbingwg/multus-cni/pull/965#issuecomment-1315172242, your PR decrease code coverage. 
We run unit test to cover the code and adding unit-test to increase code coverage. So if you don't mind, let me close this PR.

**Comment by yulng** [comment]
> Thank you for the PR, @yulng . Looking coveralls, [#965 (comment)](https://github.com/k8snetworkplumbingwg/multus-cni/pull/965#issuecomment-1315172242), your PR decrease code coverage. We run unit test to cover the code and adding unit-test to increase code coverage. So if you don't mind, let me close this PR.

ok,i closed it
could you check the other two PRs?
https://github.com/k8snetworkplumbingwg/multus-cni/pull/961
https://github.com/k8snetworkplumbingwg/multus-cni/pull/960
thanks

**Pull request closed without merging**
