### PR TITLE
remove vendoring, use Go modules

### PR DESCRIPTION
**Pull request by jaypipes**
Removes the vendor/ directory and all vestiges of life before Go modules.

Issue k8snetworkplumbingwg/sriov-network-device-plugin#544

### CODE REVIEW

**Comment by jaypipes** [comment]
@dougbtv @s1061123 Hi! Any chance to look at this PR and/or run it through the gate tests please? Thanks much in advance!

**Comment by dougbtv** [comment]
Thanks for the proposed change, I'm going to bring it to the NPWG main meeting and discuss, feel free to join, I added to the agenda for next week @ https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit

**Comment by jaypipes** [comment]
@dougbtv if you could approve the running of the workflows when you get a chance, that would be groovy, thanks! :)

**Comment by adrianchiris** [comment]
+1 on removing vendoring. we already did that did that for a bunch of projects in ngwg (sriov dp, cni, operator)

**Pull request closed without merging**
