### PR TITLE
feat: upgrade dependencies; CNI 1.1.0 support

### PR DESCRIPTION
**Pull request by buroa**
This PR support CNI SPEC 1.1.0, with new CNI commands, GC and STATUS [on top of stale [1273](https://github.com/k8snetworkplumbingwg/multus-cni/pull/1273)]

I have also upgraded all vendor dependencies. 

This is *now* required to work with `containerd` v2.0.1+

More info here: https://github.com/containerd/go-cni/pull/123

### CODE REVIEW

**Comment by buroa** [comment]
Hey @s1061123 and @dougbtv, sorry, this is a pretty big PR due to upgrading vendor dependencies. I'm also not sure if this function is correct: https://github.com/buroa/multus-cni/blob/master/pkg/kubeletclient/kubeletclient.go#L159

**Comment by dougbtv** [comment]
mind breaking out the go.mod changes from the vendoring? thanks!

**Comment by buroa** [comment]
@dougbtv Do you mean to _not_ include any vendoring/dependency/go.mod updates?

**Comment by s1061123** [comment]
Hi,

- The PR code looks same to mine. Is there any difference? Just update vendoring? I'm not quite sure that why you file another PR.
- In addition, e2e tests are failed. Could you please take a look into it?

**Pull request closed without merging**
